application:
  name: hellok8s
  hellok8s:
    image: yeader/hellok8s:v6
    replicas: 3
    message: "FXD! It works with Helm Values![v2]"
    database:
      url: "http://DB_ADDRESS_DEFAULT"
      password: "db_password"
  nginx:
    image: nginx
    replicas: 2